version: 2
jobs:
  build:
    working_directory: /go/src/github.com/weaveworks/kured
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f ./cmd/kured/Dockerfile .

      - deploy:
          name: Maybe push master images
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
              make publish-image
            fi
